# Generated by Django 4.1.1 on 2022-09-09 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=400, unique=True, verbose_name="user name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("password", models.CharField(max_length=400, verbose_name="password")),
            ],
            options={"verbose_name": "user data", "verbose_name_plural": "user data",},
        ),
    ]
