# Generated by Django 4.1.1 on 2022-09-09 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=400, verbose_name="name of visitor"),
                ),
                (
                    "first_phone_number",
                    models.IntegerField(verbose_name="first phone number"),
                ),
                (
                    "second_phone_number",
                    models.IntegerField(verbose_name="second phone number"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="nurse email"),
                ),
                (
                    "password",
                    models.CharField(max_length=400, verbose_name="nurse password"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="description about nurse"),
                ),
            ],
            options={"verbose_name": "nurse", "verbose_name_plural": "nurse",},
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=400, verbose_name="name of visitor"),
                ),
                (
                    "reason_of_visitor",
                    models.TextField(verbose_name="reason of visitor"),
                ),
                (
                    "time",
                    models.DateField(
                        default=datetime.date.today, verbose_name="date of visit"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="approved by doctor"
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="visitor_to_doctor",
                        related_query_name="visitor_to_doctor",
                        to="nurse.nurse",
                        verbose_name="added by",
                    ),
                ),
            ],
            options={"verbose_name": "visitor", "verbose_name_plural": "visitor",},
        ),
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=400, verbose_name="sick name")),
                ("phone_number", models.IntegerField(verbose_name="sick phone number")),
                (
                    "doctor_report",
                    models.TextField(
                        blank=True, null=True, verbose_name="doctor report"
                    ),
                ),
                (
                    "approved",
                    models.BooleanField(
                        default=False, verbose_name="approved by nurse"
                    ),
                ),
                (
                    "time",
                    models.DateField(
                        default=datetime.date.today, verbose_name="date of Statement"
                    ),
                ),
                (
                    "type_of_statement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "--------"),
                            ("A", "Consultation"),
                            ("B", "Statement"),
                        ],
                        default="",
                        max_length=1,
                        null=True,
                        verbose_name="type of statement",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="addded by",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="approved_by_nurse",
                        related_query_name="approved_by_nurse",
                        to="nurse.nurse",
                        verbose_name="approved by",
                    ),
                ),
            ],
        ),
    ]
