# Generated by Django 4.1.1 on 2022-09-10 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="approved_by_nurse",
                related_query_name="approved_by_nurse",
                to="nurse.nurse",
                verbose_name="approved by",
            ),
        ),
        migrations.AlterField(
            model_name="row",
            name="type_of_statement",
            field=models.CharField(
                choices=[("", "--------"), ("A", "Consultation"), ("B", "Statement")],
                default="",
                max_length=1,
                verbose_name="type of statement",
            ),
        ),
    ]
