# Generated by Django 4.1.1 on 2022-09-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0002_alter_row_approved_by_alter_row_type_of_statement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="approved_by_nurse",
                related_query_name="approved_by_nurse",
                to="nurse.nurse",
                verbose_name="approved by",
            ),
        ),
    ]
