# Generated by Django 4.1.1 on 2022-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0003_alter_row_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="row",
            name="name",
            field=models.TextField(verbose_name="sick name"),
        ),
    ]
