# Generated by Django 4.1.1 on 2022-09-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0004_alter_row_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="row", options={"verbose_name": "Sick", "verbose_name_plural": "Sick"},
        ),
    ]
