# Generated by Django 4.1.1 on 2022-09-10 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0005_alter_row_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="nurse email"
            ),
        ),
    ]
