# Generated by Django 4.1.1 on 2022-09-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nurse", "0006_alter_nurse_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nurse",
            name="second_phone_number",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="second phone number"
            ),
        ),
    ]
