# Generated by Django 4.1.1 on 2022-09-09 22:10

import datetime
from django.db import migrations, models
import doctor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(verbose_name="addrees")),
                ("note", models.TextField(verbose_name="note")),
                ("from_time", models.TimeField(verbose_name="when open")),
                ("to_time", models.TimeField(verbose_name="when close")),
                ("time_of_vacation", models.TextField(verbose_name="time of vacation")),
            ],
            options={
                "verbose_name": "clinic data",
                "verbose_name_plural": "clinic data",
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="name of doctor")),
                (
                    "phone_number",
                    models.IntegerField(verbose_name="doctor phone number"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="doctor email"),
                ),
                (
                    "password",
                    models.CharField(max_length=400, verbose_name="doctor password"),
                ),
                ("description", models.TextField(verbose_name="doctor description")),
                (
                    "pic",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=doctor.models.update_pic_filename,
                        verbose_name="صورة",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor data",
                "verbose_name_plural": "Doctor data",
            },
        ),
        migrations.CreateModel(
            name="Fees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=400, verbose_name="type of fees")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=3, max_digits=3, verbose_name="price fees"
                    ),
                ),
                (
                    "time",
                    models.DateField(
                        default=datetime.date.today, verbose_name="time of fees"
                    ),
                ),
            ],
            options={
                "verbose_name": "details of fees",
                "verbose_name_plural": "details of fees",
            },
        ),
    ]
