# Generated by Django 4.1.1 on 2022-09-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="doctor email"
            ),
        ),
        migrations.AlterField(
            model_name="fees",
            name="price",
            field=models.DecimalField(
                decimal_places=3, max_digits=7, verbose_name="price fees"
            ),
        ),
    ]
